# Generated by Django 3.2.14 on 2022-08-27 13:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_commodity_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='brand'),
            preserve_default=False,
        ),
    ]
