# Generated by Django 3.2.14 on 2022-08-29 08:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20220829_0244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='tel',
            field=phone_field.models.PhoneField(blank=True, max_length=31, null=True),
        ),
    ]
