# Generated by Django 3.2.14 on 2022-09-01 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_commodity_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commodity',
            name='slug',
        ),
    ]
