# Generated by Django 3.2.14 on 2022-09-01 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0014_commodity_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commodity',
            old_name='slug',
            new_name='slug1',
        ),
    ]
