# Generated by Django 3.2.14 on 2022-09-02 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_rename_slug_commodity_slug1'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='classes'),
        ),
        migrations.AddField(
            model_name='classes',
            name='sub_clas',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classes',
            name='sub_classes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub', to='catalog.classes'),
        ),
        migrations.RemoveField(
            model_name='commodity',
            name='classes',
        ),
        migrations.AddField(
            model_name='commodity',
            name='classes',
            field=models.ManyToManyField(blank=True, to='catalog.Classes'),
        ),
    ]
