# Generated by Django 3.2.14 on 2022-09-03 14:52

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_remove_classes_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='information',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
