# Generated by Django 3.2.14 on 2022-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_commodity_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='information',
            field=models.TextField(blank=True, null=True),
        ),
    ]
