# Generated by Django 3.2.14 on 2022-09-03 22:40

import ckeditor.fields
from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0005_auto_20220424_2025'),
        ('catalog', '0020_alter_commodity_information'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='information',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
