# Generated by Django 3.2.14 on 2022-09-04 15:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0021_auto_20220904_0310'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_product', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commodity',
            name='unlike',
            field=models.ManyToManyField(blank=True, related_name='unlike_product', to=settings.AUTH_USER_MODEL),
        ),
    ]
