# Generated by Django 3.2.14 on 2022-09-07 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0025_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='amount',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
