# Generated by Django 3.2.14 on 2022-09-11 19:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalog', '0026_commodity_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='fa_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
