# Generated by Django 3.2.14 on 2022-09-11 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'verbose_name': 'خرید', 'verbose_name_plural': 'خرید ها'},
        ),
    ]
